// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (user_id, weight, height, body_fat, activity_level, bmi, bmr, tdee)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, weight, height, body_fat, activity_level, bmi, bmr, tdee, created_at, updated_at, deleted_at
`

type CreateAssessmentParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Weight        float64   `json:"weight"`
	Height        float64   `json:"height"`
	BodyFat       float64   `json:"body_fat"`
	ActivityLevel string    `json:"activity_level"`
	Bmi           float64   `json:"bmi"`
	Bmr           float64   `json:"bmr"`
	Tdee          float64   `json:"tdee"`
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, createAssessment,
		arg.UserID,
		arg.Weight,
		arg.Height,
		arg.BodyFat,
		arg.ActivityLevel,
		arg.Bmi,
		arg.Bmr,
		arg.Tdee,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weight,
		&i.Height,
		&i.BodyFat,
		&i.ActivityLevel,
		&i.Bmi,
		&i.Bmr,
		&i.Tdee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssessmentById = `-- name: GetAssessmentById :one
SELECT id, user_id, weight, height, body_fat, activity_level, bmi, bmr, tdee, created_at, updated_at, deleted_at FROM assessments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAssessmentById(ctx context.Context, id uuid.UUID) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, getAssessmentById, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weight,
		&i.Height,
		&i.BodyFat,
		&i.ActivityLevel,
		&i.Bmi,
		&i.Bmr,
		&i.Tdee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestAssessmentByUserID = `-- name: GetLatestAssessmentByUserID :one
SELECT id, user_id, weight, height, body_fat, activity_level, bmi, bmr, tdee, created_at, updated_at, deleted_at FROM assessments
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAssessmentByUserID(ctx context.Context, userID uuid.UUID) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, getLatestAssessmentByUserID, userID)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weight,
		&i.Height,
		&i.BodyFat,
		&i.ActivityLevel,
		&i.Bmi,
		&i.Bmr,
		&i.Tdee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssessmentsByUser = `-- name: ListAssessmentsByUser :many
SELECT id, user_id, weight, height, body_fat, activity_level, bmi, bmr, tdee, created_at, updated_at, deleted_at FROM assessments
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAssessmentsByUser(ctx context.Context, userID uuid.UUID) ([]Assessment, error) {
	rows, err := q.db.QueryContext(ctx, listAssessmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Weight,
			&i.Height,
			&i.BodyFat,
			&i.ActivityLevel,
			&i.Bmi,
			&i.Bmr,
			&i.Tdee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAssessment = `-- name: SoftDeleteAssessment :exec
UPDATE assessments SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAssessment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteAssessment, id)
	return err
}

const updateAssessment = `-- name: UpdateAssessment :one
UPDATE assessments
SET
    weight = $2,
    height = $3,
    body_fat = $4,
    activity_level = $5,
    bmi = $6,
    bmr = $7,
    tdee = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, weight, height, body_fat, activity_level, bmi, bmr, tdee, created_at, updated_at, deleted_at
`

type UpdateAssessmentParams struct {
	ID            uuid.UUID `json:"id"`
	Weight        float64   `json:"weight"`
	Height        float64   `json:"height"`
	BodyFat       float64   `json:"body_fat"`
	ActivityLevel string    `json:"activity_level"`
	Bmi           float64   `json:"bmi"`
	Bmr           float64   `json:"bmr"`
	Tdee          float64   `json:"tdee"`
}

func (q *Queries) UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRowContext(ctx, updateAssessment,
		arg.ID,
		arg.Weight,
		arg.Height,
		arg.BodyFat,
		arg.ActivityLevel,
		arg.Bmi,
		arg.Bmr,
		arg.Tdee,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weight,
		&i.Height,
		&i.BodyFat,
		&i.ActivityLevel,
		&i.Bmi,
		&i.Bmr,
		&i.Tdee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
