// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diet_plans.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDietPlan = `-- name: CreateDietPlan :one
INSERT INTO diet_plans (protocol_id, calorie_intensity, protein_intensity, fat_intensity, protein, carbs, fat, calories, water)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, protocol_id, calorie_intensity, protein_intensity, fat_intensity, protein, carbs, fat, calories, water, is_active, created_at, updated_at, deleted_at
`

type CreateDietPlanParams struct {
	ProtocolID       uuid.UUID `json:"protocol_id"`
	CalorieIntensity string    `json:"calorie_intensity"`
	ProteinIntensity string    `json:"protein_intensity"`
	FatIntensity     string    `json:"fat_intensity"`
	Protein          float64   `json:"protein"`
	Carbs            float64   `json:"carbs"`
	Fat              float64   `json:"fat"`
	Calories         float64   `json:"calories"`
	Water            float64   `json:"water"`
}

func (q *Queries) CreateDietPlan(ctx context.Context, arg CreateDietPlanParams) (DietPlan, error) {
	row := q.db.QueryRowContext(ctx, createDietPlan,
		arg.ProtocolID,
		arg.CalorieIntensity,
		arg.ProteinIntensity,
		arg.FatIntensity,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Calories,
		arg.Water,
	)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.CalorieIntensity,
		&i.ProteinIntensity,
		&i.FatIntensity,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
		&i.Water,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDietPlanById = `-- name: GetDietPlanById :one
SELECT id, protocol_id, calorie_intensity, protein_intensity, fat_intensity, protein, carbs, fat, calories, water, is_active, created_at, updated_at, deleted_at FROM diet_plans
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDietPlanById(ctx context.Context, id uuid.UUID) (DietPlan, error) {
	row := q.db.QueryRowContext(ctx, getDietPlanById, id)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.CalorieIntensity,
		&i.ProteinIntensity,
		&i.FatIntensity,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
		&i.Water,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDietPlansByProtocol = `-- name: ListDietPlansByProtocol :many
SELECT id, protocol_id, calorie_intensity, protein_intensity, fat_intensity, protein, carbs, fat, calories, water, is_active, created_at, updated_at, deleted_at FROM diet_plans
WHERE protocol_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDietPlansByProtocol(ctx context.Context, protocolID uuid.UUID) ([]DietPlan, error) {
	rows, err := q.db.QueryContext(ctx, listDietPlansByProtocol, protocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DietPlan
	for rows.Next() {
		var i DietPlan
		if err := rows.Scan(
			&i.ID,
			&i.ProtocolID,
			&i.CalorieIntensity,
			&i.ProteinIntensity,
			&i.FatIntensity,
			&i.Protein,
			&i.Carbs,
			&i.Fat,
			&i.Calories,
			&i.Water,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDietPlan = `-- name: SoftDeleteDietPlan :exec
UPDATE diet_plans SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDietPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteDietPlan, id)
	return err
}

const updateDietPlan = `-- name: UpdateDietPlan :one
UPDATE diet_plans
SET
    calorie_intensity = $2,
    protein_intensity = $3,
    fat_intensity    = $4,
    protein   = $5,
    carbs     = $6,
    fat       = $7,
    calories  = $8,
    water     = $9,
    is_active = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, protocol_id, calorie_intensity, protein_intensity, fat_intensity, protein, carbs, fat, calories, water, is_active, created_at, updated_at, deleted_at
`

type UpdateDietPlanParams struct {
	ID               uuid.UUID    `json:"id"`
	CalorieIntensity string       `json:"calorie_intensity"`
	ProteinIntensity string       `json:"protein_intensity"`
	FatIntensity     string       `json:"fat_intensity"`
	Protein          float64      `json:"protein"`
	Carbs            float64      `json:"carbs"`
	Fat              float64      `json:"fat"`
	Calories         float64      `json:"calories"`
	Water            float64      `json:"water"`
	IsActive         sql.NullBool `json:"is_active"`
}

func (q *Queries) UpdateDietPlan(ctx context.Context, arg UpdateDietPlanParams) (DietPlan, error) {
	row := q.db.QueryRowContext(ctx, updateDietPlan,
		arg.ID,
		arg.CalorieIntensity,
		arg.ProteinIntensity,
		arg.FatIntensity,
		arg.Protein,
		arg.Carbs,
		arg.Fat,
		arg.Calories,
		arg.Water,
		arg.IsActive,
	)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ProtocolID,
		&i.CalorieIntensity,
		&i.ProteinIntensity,
		&i.FatIntensity,
		&i.Protein,
		&i.Carbs,
		&i.Fat,
		&i.Calories,
		&i.Water,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
