// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (project_id, name, strategy_type)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, strategy_type, is_active, created_at, updated_at, deleted_at
`

type CreateGoalParams struct {
	ProjectID    uuid.UUID `json:"project_id"`
	Name         string    `json:"name"`
	StrategyType string    `json:"strategy_type"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal, arg.ProjectID, arg.Name, arg.StrategyType)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.StrategyType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoalById = `-- name: GetGoalById :one
SELECT id, project_id, name, strategy_type, is_active, created_at, updated_at, deleted_at FROM goals
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGoalById(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalById, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.StrategyType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGoalsByProject = `-- name: ListGoalsByProject :many
SELECT id, project_id, name, strategy_type, is_active, created_at, updated_at, deleted_at FROM goals
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListGoalsByProject(ctx context.Context, projectID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoalsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.StrategyType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGoal = `-- name: SoftDeleteGoal :exec
UPDATE goals SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteGoal, id)
	return err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET
    name = $2,
    strategy_type = $3,
    is_active = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, name, strategy_type, is_active, created_at, updated_at, deleted_at
`

type UpdateGoalParams struct {
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	StrategyType string       `json:"strategy_type"`
	IsActive     sql.NullBool `json:"is_active"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.ID,
		arg.Name,
		arg.StrategyType,
		arg.IsActive,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.StrategyType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
