// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: macro_estimations.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMacroEstimation = `-- name: CreateMacroEstimation :one
INSERT INTO macro_estimations (user_id, meal_description, meal_items)
VALUES ($1, $2, $3)
RETURNING id, user_id, meal_description, meal_items, created_at, updated_at, deleted_at
`

type CreateMacroEstimationParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	MealDescription string          `json:"meal_description"`
	MealItems       json.RawMessage `json:"meal_items"`
}

func (q *Queries) CreateMacroEstimation(ctx context.Context, arg CreateMacroEstimationParams) (MacroEstimation, error) {
	row := q.db.QueryRowContext(ctx, createMacroEstimation, arg.UserID, arg.MealDescription, arg.MealItems)
	var i MacroEstimation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealDescription,
		&i.MealItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMacroEstimationById = `-- name: GetMacroEstimationById :one
SELECT id, user_id, meal_description, meal_items, created_at, updated_at, deleted_at FROM macro_estimations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMacroEstimationById(ctx context.Context, id uuid.UUID) (MacroEstimation, error) {
	row := q.db.QueryRowContext(ctx, getMacroEstimationById, id)
	var i MacroEstimation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealDescription,
		&i.MealItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMacroEstimationsByUser = `-- name: ListMacroEstimationsByUser :many
SELECT id, user_id, meal_description, meal_items, created_at, updated_at, deleted_at FROM macro_estimations
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMacroEstimationsByUser(ctx context.Context, userID uuid.UUID) ([]MacroEstimation, error) {
	rows, err := q.db.QueryContext(ctx, listMacroEstimationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MacroEstimation
	for rows.Next() {
		var i MacroEstimation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MealDescription,
			&i.MealItems,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMacroEstimation = `-- name: SoftDeleteMacroEstimation :exec
UPDATE macro_estimations SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMacroEstimation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteMacroEstimation, id)
	return err
}
