// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_logs.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMealLog = `-- name: CreateMealLog :one
INSERT INTO meal_logs (user_id, meal_title, meal_description, meal_items)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, meal_title, meal_description, meal_items, created_at, updated_at, deleted_at
`

type CreateMealLogParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	MealTitle       string          `json:"meal_title"`
	MealDescription string          `json:"meal_description"`
	MealItems       json.RawMessage `json:"meal_items"`
}

func (q *Queries) CreateMealLog(ctx context.Context, arg CreateMealLogParams) (MealLog, error) {
	row := q.db.QueryRowContext(ctx, createMealLog,
		arg.UserID,
		arg.MealTitle,
		arg.MealDescription,
		arg.MealItems,
	)
	var i MealLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealTitle,
		&i.MealDescription,
		&i.MealItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMealLogById = `-- name: GetMealLogById :one
SELECT id, user_id, meal_title, meal_description, meal_items, created_at, updated_at, deleted_at FROM meal_logs
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMealLogById(ctx context.Context, id uuid.UUID) (MealLog, error) {
	row := q.db.QueryRowContext(ctx, getMealLogById, id)
	var i MealLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealTitle,
		&i.MealDescription,
		&i.MealItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMealLogsByUser = `-- name: ListMealLogsByUser :many
SELECT id, user_id, meal_title, meal_description, meal_items, created_at, updated_at, deleted_at FROM meal_logs
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMealLogsByUser(ctx context.Context, userID uuid.UUID) ([]MealLog, error) {
	rows, err := q.db.QueryContext(ctx, listMealLogsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealLog
	for rows.Next() {
		var i MealLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MealTitle,
			&i.MealDescription,
			&i.MealItems,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMealLog = `-- name: SoftDeleteMealLog :exec
UPDATE meal_logs SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMealLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteMealLog, id)
	return err
}

const updateMealLog = `-- name: UpdateMealLog :one
UPDATE meal_logs
SET
    meal_title = $2,
    meal_description = $3,
    meal_items = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, meal_title, meal_description, meal_items, created_at, updated_at, deleted_at
`

type UpdateMealLogParams struct {
	ID              uuid.UUID       `json:"id"`
	MealTitle       string          `json:"meal_title"`
	MealDescription string          `json:"meal_description"`
	MealItems       json.RawMessage `json:"meal_items"`
}

func (q *Queries) UpdateMealLog(ctx context.Context, arg UpdateMealLogParams) (MealLog, error) {
	row := q.db.QueryRowContext(ctx, updateMealLog,
		arg.ID,
		arg.MealTitle,
		arg.MealDescription,
		arg.MealItems,
	)
	var i MealLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealTitle,
		&i.MealDescription,
		&i.MealItems,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
