// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: protocols.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProtocol = `-- name: CreateProtocol :one
INSERT INTO protocols (goal_id, name)
VALUES ($1, $2)
RETURNING id, goal_id, name, is_active, created_at, updated_at, deleted_at
`

type CreateProtocolParams struct {
	GoalID uuid.UUID `json:"goal_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateProtocol(ctx context.Context, arg CreateProtocolParams) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, createProtocol, arg.GoalID, arg.Name)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProtocolById = `-- name: GetProtocolById :one
SELECT id, goal_id, name, is_active, created_at, updated_at, deleted_at FROM protocols
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProtocolById(ctx context.Context, id uuid.UUID) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, getProtocolById, id)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProtocolsByGoal = `-- name: ListProtocolsByGoal :many
SELECT id, goal_id, name, is_active, created_at, updated_at, deleted_at FROM protocols
WHERE goal_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProtocolsByGoal(ctx context.Context, goalID uuid.UUID) ([]Protocol, error) {
	rows, err := q.db.QueryContext(ctx, listProtocolsByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Protocol
	for rows.Next() {
		var i Protocol
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProtocol = `-- name: SoftDeleteProtocol :exec
UPDATE protocols SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProtocol(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProtocol, id)
	return err
}

const updateProtocol = `-- name: UpdateProtocol :one
UPDATE protocols
SET
    name = $2,
    is_active = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, goal_id, name, is_active, created_at, updated_at, deleted_at
`

type UpdateProtocolParams struct {
	ID       uuid.UUID    `json:"id"`
	Name     string       `json:"name"`
	IsActive sql.NullBool `json:"is_active"`
}

func (q *Queries) UpdateProtocol(ctx context.Context, arg UpdateProtocolParams) (Protocol, error) {
	row := q.db.QueryRowContext(ctx, updateProtocol, arg.ID, arg.Name, arg.IsActive)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
