// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error)
	CreateDietPlan(ctx context.Context, arg CreateDietPlanParams) (DietPlan, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateMacroEstimation(ctx context.Context, arg CreateMacroEstimationParams) (MacroEstimation, error)
	CreateMealLog(ctx context.Context, arg CreateMealLogParams) (MealLog, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProtocol(ctx context.Context, arg CreateProtocolParams) (Protocol, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAssessmentById(ctx context.Context, id uuid.UUID) (Assessment, error)
	GetDietPlanById(ctx context.Context, id uuid.UUID) (DietPlan, error)
	GetGoalById(ctx context.Context, id uuid.UUID) (Goal, error)
	GetLatestAssessmentByUserID(ctx context.Context, userID uuid.UUID) (Assessment, error)
	GetMacroEstimationById(ctx context.Context, id uuid.UUID) (MacroEstimation, error)
	GetMealLogById(ctx context.Context, id uuid.UUID) (MealLog, error)
	GetProjectById(ctx context.Context, id uuid.UUID) (Project, error)
	GetProtocolById(ctx context.Context, id uuid.UUID) (Protocol, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	ListAssessmentsByUser(ctx context.Context, userID uuid.UUID) ([]Assessment, error)
	ListDietPlansByProtocol(ctx context.Context, protocolID uuid.UUID) ([]DietPlan, error)
	ListGoalsByProject(ctx context.Context, projectID uuid.UUID) ([]Goal, error)
	ListMacroEstimationsByUser(ctx context.Context, userID uuid.UUID) ([]MacroEstimation, error)
	ListMealLogsByUser(ctx context.Context, userID uuid.UUID) ([]MealLog, error)
	ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error)
	ListProtocolsByGoal(ctx context.Context, goalID uuid.UUID) ([]Protocol, error)
	ListUsers(ctx context.Context) ([]User, error)
	SoftDeleteAssessment(ctx context.Context, id uuid.UUID) error
	SoftDeleteDietPlan(ctx context.Context, id uuid.UUID) error
	SoftDeleteGoal(ctx context.Context, id uuid.UUID) error
	SoftDeleteMacroEstimation(ctx context.Context, id uuid.UUID) error
	SoftDeleteMealLog(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteProtocol(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateAssessment(ctx context.Context, arg UpdateAssessmentParams) (Assessment, error)
	UpdateDietPlan(ctx context.Context, arg UpdateDietPlanParams) (DietPlan, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateMealLog(ctx context.Context, arg UpdateMealLogParams) (MealLog, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProtocol(ctx context.Context, arg UpdateProtocolParams) (Protocol, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
