import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/onboarding');
  await page.getByRole('button', { name: 'Get started' }).click();
  await page.getByRole('textbox', { name: 'e.g. Alex Costa' }).click();
  await page.getByRole('textbox', { name: 'e.g. Alex Costa' }).fill('Augusto Cardoso dos Santos');
  await page.getByRole('textbox', { name: 'e.g. Alex Costa' }).press('Tab');
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('acardoso.ti@gmail.com');
  await page.getByRole('textbox', { name: 'you@example.com' }).press('Tab');
  await page.locator('input[type="date"]').fill('1994-11-17');
  await page.locator('input[type="date"]').press('Tab');
  await page.getByRole('combobox').selectOption('male');
  await page.getByRole('button', { name: 'Create profile' }).click();
  await page.getByPlaceholder('175').click();
  await page.getByPlaceholder('175').fill('160');
  await page.getByPlaceholder('175').press('Tab');
  await page.getByPlaceholder('75', { exact: true }).fill('84.1');
  await page.getByPlaceholder('18').click();
  await page.getByPlaceholder('18').fill('30.4');
  await page.getByPlaceholder('18').press('Tab');
  await page.getByRole('combobox').selectOption('moderately_active');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('textbox', { name: 'My Fitness Project' }).click();
  await page.getByRole('textbox', { name: 'My Fitness Project' }).fill('Body Recomposition');
  await page.getByRole('textbox', { name: 'My Fitness Project' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'My Fitness Project' }).press('ControlOrMeta+c');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('textbox', { name: 'My Goal' }).click();
  await page.getByRole('textbox', { name: 'My Goal' }).fill('Body Recomposition');
  await page.getByRole('combobox').selectOption('recomposition');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('textbox', { name: 'My Protocol' }).click();
  await page.getByRole('textbox', { name: 'My Protocol' }).fill('Body Recomposition');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('combobox').first().selectOption('moderate');
  await page.getByRole('combobox').nth(1).selectOption('moderate');
  await page.getByRole('combobox').nth(2).selectOption('moderate');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Go to dashboard' }).click();
});